import OpenAI from 'openai';
import prisma from '../utils/prisma.js';

export interface IntentResult {
    intent: 'SIGNUP' | 'SEND_FUNDS' | 'INTERNATIONAL_TRANSFER' | 'PAY_BILL' | 'CHECK_BALANCE' | 'INVOICE' | 'CRYPTO' | 'CARD' | 'GIFTCARD' | 'OPEN_ACCOUNT' | 'SCHEDULE_TASK' | 'CONVERT' | 'GENERATE_VOUCHER' | 'REDEEM_VOUCHER' | 'CHECK_BUDGET' | 'UNKNOWN';
    entities?: {
        amount?: number;
        recipient?: string;
        billType?: string;
        asset?: string;
        currency?: string;
        country?: string;
        date?: string; // For scheduling
        priceCondition?: number; // For "Buy the Dip"
        recurring?: boolean;
        language?: string; // For translation logic
    };
    response?: string;
    actions?: string[]; // A sequence of actions to perform
    replyText?: string; // Conversational response explicitly generated by AI
}

export interface ConversationMessage {
    role: 'user' | 'assistant';
    content: string;
    timestamp?: Date;
}

export interface UserProfileContext {
    kycStatus?: string;
    balance?: number;
    accountNumber?: string;
    bankName?: string;
    currentState?: string;
    userName?: string;
    phoneNumber?: string;
    email?: string;
    tier?: number;
    memberSince?: string;
    recentTransactions?: string;
    conversationHistory?: ConversationMessage[];
}

export class AiService {
    private openai: OpenAI;

    private async getOpenAI(): Promise<OpenAI | null> {
        if (this.openai) return this.openai;
        
        try {
            const config = await prisma.systemConfig.findUnique({ where: { id: 'global' } });
            const key = config?.openaiKey || process.env.OPENAI_API_KEY;
            
            if (key && key !== 'your_openai_api_key_here' && key !== '') {
                this.openai = new OpenAI({ apiKey: key });
                return this.openai;
            }
        } catch (e) {}
        return null;
    }

    /**
     * Fetches the last N conversation messages for a user to build memory context.
     */
    async getConversationHistory(userId: string, limit: number = 20): Promise<ConversationMessage[]> {
        try {
            const logs = await prisma.conversationLog.findMany({
                where: { userId },
                orderBy: { createdAt: 'desc' },
                take: limit,
                select: {
                    direction: true,
                    message: true,
                    intent: true,
                    createdAt: true
                }
            });

            // Reverse to chronological order (oldest first)
            return logs.reverse().map(log => ({
                role: log.direction === 'INBOUND' ? 'user' as const : 'assistant' as const,
                content: log.message,
                timestamp: log.createdAt
            }));
        } catch (e) {
            console.error('[AI Memory] Failed to fetch conversation history:', e);
            return [];
        }
    }

    /**
     * Fetches recent transaction summaries for a user.
     */
    async getRecentTransactions(userId: string, limit: number = 10): Promise<string> {
        try {
            const txns = await prisma.transaction.findMany({
                where: { userId },
                orderBy: { createdAt: 'desc' },
                take: limit,
                select: {
                    type: true,
                    amount: true,
                    currency: true,
                    status: true,
                    description: true,
                    createdAt: true
                }
            });

            if (txns.length === 0) return 'No transactions yet.';

            return txns.map(tx => 
                `[${tx.createdAt.toLocaleDateString()}] ${tx.type}: ${tx.currency} ${tx.amount.toLocaleString()} — ${tx.description || 'N/A'} (${tx.status})`
            ).join('\n');
        } catch (e) {
            console.error('[AI Memory] Failed to fetch transactions:', e);
            return 'Transaction history unavailable.';
        }
    }

    /**
     * Builds a rich user profile summary for the AI context window.
     */
    async buildUserProfile(userId: string): Promise<{ profile: string; transactions: string }> {
        try {
            const user = await prisma.user.findUnique({
                where: { id: userId },
                include: {
                    virtualAccounts: { where: { isActive: true }, take: 5 },
                    businessKyb: true
                }
            });

            if (!user) return { profile: 'Unknown user.', transactions: 'N/A' };

            const accounts = user.virtualAccounts.map(va =>
                `${va.currency} Account: ${va.accountNumber} (${va.bankName})`
            ).join(', ') || 'No virtual accounts';

            const businessInfo = user.businessKyb ? 
                `Business: CAC ${user.businessKyb.cacNumber}${user.businessKyb.companyName ? ' — ' + user.businessKyb.companyName : ''} (${user.businessKyb.status})` : '';

            const profile = [
                `Name: ${user.name || 'Not set'}`,
                `Phone: ${user.phoneNumber}`,
                `Email: ${user.email || 'Not linked'}`,
                `KYC Status: ${user.kycStatus}`,
                `Member Since: ${user.createdAt.toLocaleDateString()}`,
                `Account Tier: ${user.tier}`,
                `Accounts: ${accounts}`,
                businessInfo,
                `PIN Set: ${user.transactionPin ? 'Yes' : 'No'}`,
                `Suspended: ${user.suspended ? 'YES' : 'No'}`
            ].filter(Boolean).join('\n');

            const transactions = await this.getRecentTransactions(userId);

            return { profile, transactions };
        } catch (e) {
            console.error('[AI Memory] Failed to build user profile:', e);
            return { profile: 'Profile unavailable.', transactions: 'N/A' };
        }
    }

    async parseIntent(message: string, context?: UserProfileContext): Promise<IntentResult> {
        const openai = await this.getOpenAI();
        if (!openai) {
            console.log(`[MOCK AI] No API key, using mock for: "${message}"`);
            const lower = message.toLowerCase();
            const greetings = ['hi', 'hello', 'hey', 'yo', 'sup', 'morning', 'afternoon', 'evening', '👋'];
            if (greetings.some(g => lower.includes(g))) return { intent: 'SIGNUP' };
            if (lower.includes('send') || lower.includes('pay') || lower.includes('transfer')) return { intent: 'SEND_FUNDS', entities: { amount: 2500, recipient: 'Peter' } };
            return { intent: 'UNKNOWN' };
        }
        try {
            // Build conversation history for the messages array
            const messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }> = [];

            const systemPrompt = `
                You are ChatPay AI Agent, a sophisticated multi-step financial assistant on WhatsApp. 
                You have LONG-TERM MEMORY — you remember every past conversation with this user.
                Extract intent, entities, and required ACTIONS.
                We speak English, Pidgin, Yoruba, Igbo, and Hausa.

                === USER PROFILE ===
                Name: ${context?.userName || 'Unknown'}
                Phone: ${context?.phoneNumber || 'N/A'}
                Email: ${context?.email || 'Not linked'}
                KYC: ${context?.kycStatus || 'PENDING'}
                Tier: ${context?.tier || 0}
                Member Since: ${context?.memberSince || 'Unknown'}
                Current Balance: ₦${context?.balance || 0}
                NGN Account: ${context?.accountNumber ? context.bankName + ' / ' + context.accountNumber : 'None Setup'}
                Current Flow State: ${context?.currentState || 'START'}
                
                === RECENT TRANSACTIONS ===
                ${context?.recentTransactions || 'None'}
                
                === MISSION TRACKING ===
                If 'Current Flow State' is NOT 'START', the user is likely responding to your previous question. 
                If the state is 'AWAITING_ACCOUNT_TYPE', and they say 'Individual', your intent is 'SIGNUP'.
                If you just asked 'Ready to proceed?' and they say 'Yes', continue the current mission.
                
                === BEHAVIORAL RULES ===
                1. DYNAMIC RESPONSE: Always provide "replyText" — the EXACT conversational text to send back.
                2. LANGUAGE MIRRORING: Respond in the SAME language/dialect the user uses. If Pidgin, respond in Pidgin. If Yoruba, Yoruba.
                3. ALWAYS BE CLOSING: Never end without a call-to-action in the user's language.
                4. CONTEXT AWARENESS: Use the user's profile, transaction history, and past conversations to give PERSONALIZED, ACCURATE responses.
                5. MEMORY: You have access to the conversation history below. Reference past interactions naturally. If a user asks "what's my name?", you know it. If they ask "what was my last transaction?", you can tell them.
                6. ACCURACY: Never make up information. Only use the data provided in the user profile and conversation history. If you don't know something, say so honestly and direct them to the appropriate action.
                7. PROACTIVE: If you notice patterns (e.g., user frequently buys airtime), suggest relevant features.
                8. NEVER expose sensitive data like BVN, full PINs, or API keys in your responses.
                
                Intents: SIGNUP, SEND_FUNDS, INTERNATIONAL_TRANSFER, PAY_BILL, CHECK_BALANCE, INVOICE, CRYPTO, CARD, GIFTCARD, OPEN_ACCOUNT, SCHEDULE_TASK, CONVERT, FUND_WALLET, BETTING, MARKET_REPORT, UNKNOWN.
                
                Examples:
                1. "Abeg send 10k to Peter" (Pidgin) -> { "intent": "SEND_FUNDS", "entities": { "amount": 10000, "recipient": "Peter" }, "replyText": "Done! I dey send ₦10,000 to Peter now. You wan send to person again?" }
                2. "What's my balance?" -> { "intent": "CHECK_BALANCE", "replyText": "Your current balance is ₦{balance}. Would you like to send money or pay a bill?" }
                3. "What was my last transaction?" -> { "intent": "UNKNOWN", "replyText": "Your most recent transaction was [info from history]. Need help with anything else?" }
                4. "Who am I?" -> { "intent": "UNKNOWN", "replyText": "You're {name}! You've been with ChatPay since {date}. How can I help you today?" }
                
                Return JSON containing "intent", "entities", "actions", and "replyText".
            `;

            messages.push({ role: 'system', content: systemPrompt });

            // Inject conversation history as prior messages (last 20 exchanges)
            if (context?.conversationHistory && context.conversationHistory.length > 0) {
                for (const msg of context.conversationHistory) {
                    // Skip very long messages and system-generated button IDs
                    const content = msg.content;
                    if (content.length > 500) {
                        // Truncate long messages to keep within token limits
                        messages.push({ 
                            role: msg.role, 
                            content: content.substring(0, 500) + '...' 
                        });
                    } else if (!content.startsWith('FLOW_RESPONSE_') && content !== 'REFRESH') {
                        messages.push({ role: msg.role, content });
                    }
                }
            }

            // Add the current message
            messages.push({ role: 'user', content: message });

            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages,
                response_format: { type: "json_object" },
                temperature: 0.4, // Lower temperature for more consistent, factual responses
                max_tokens: 800
            });

            const content = response.choices[0].message.content;
            return JSON.parse(content || '{}') as IntentResult;
        } catch (error) {
            console.error('Error in AiService:', error);
            return { intent: 'UNKNOWN' };
        }
    }

    async generateResponse(prompt: string): Promise<string> {
        const openai = await this.getOpenAI();
        if (!openai) {
            return "Mock AI Response: How can I help you with your ChatPay wallet today?";
        }
        try {
            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [{ role: "user", content: prompt }]
            });
            return response.choices[0].message.content || "I'm sorry, I didn't quite catch that.";
        } catch (error) {
            console.error('Error generating AI response:', error);
            return "I'm having trouble thinking right now. Please try again later.";
        }
    }

    /**
     * Agent Vision: Scrapes data from a document or image
     */
    async scrapeDocument(buffer: Buffer, mimeType: string): Promise<any> {
        const openai = await this.getOpenAI();
        if (!openai) return { error: "Vision AI unavailable" };

        const supportedTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
        if (!supportedTypes.includes(mimeType)) {
            console.log(`[AI Vision] Unsupported mime type: ${mimeType}`);
            return { error: `Unsupported file type: ${mimeType}. Please send an image (JPG/PNG).` };
        }

        try {
            const base64 = buffer.toString('base64');
            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [
                    {
                        role: "system",
                        content: "You are a specialized Fintech Agent with Vision. If this is an invoice/receipt, extract 'BeneficiaryName', 'BankName', 'AccountNumber', and 'Amount' (as NGN value). If it is NOT an invoice (e.g. a face, a pet, or a general chat screenshot), return a field called 'description' with a short summary of what you see. Always return JSON."
                    },
                    {
                        role: "user",
                        content: [
                            { type: "text", text: "Look at this image and tell me what it is or extract the payment info if it's a bill." },
                            { type: "image_url", image_url: { url: `data:${mimeType};base64,${base64}` } }
                        ]
                    }
                ],
                response_format: { type: "json_object" }
            });

            return JSON.parse(response.choices[0].message.content || '{}');
        } catch (error) {
            console.error('[AI Vision] Scrape failed:', error);
            return null;
        }
    }

    /**
     * Agent Advisor: Performs a deep dive into user spending habits
     */
    async analyzeSpending(transactions: any[]): Promise<string> {
        const openai = await this.getOpenAI();
        if (!openai) return "Budgeting logic unavailable.";

        try {
            const txSummary = transactions.map(tx => `[${tx.createdAt}] ${tx.type}: ₦${tx.amount} (${tx.description})`).join('\n');
            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [
                    {
                        role: "system",
                        content: "You are a professional Financial Advisor for ChatPay. Analyze the user's spending habits and provide a concise, helpful summary in second-person. Highlight trends, high spending categories, and offer one practical saving tip. Be friendly and professional."
                    },
                    {
                        role: "user",
                        content: `Here is my transaction history for the last period:\n\n${txSummary}`
                    }
                ]
            });

            return response.choices[0].message.content || "I'm still analyzing your data. Check back soon!";
        } catch (error) {
            console.error('[AI Advisor] Analysis failed:', error);
            return "I couldn't analyze your spending at this time.";
        }
    }
}

export const aiService = new AiService();
