import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export const generateRoadmap = async (outputPath: string) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    doc.pipe(fs.createWriteStream(outputPath));

    // Colors
    const primaryColor = '#25D366';
    const secondaryColor = '#128C7E';
    const darkColor = '#111b21';
    const accentColor = '#00a884';

    // Header
    doc.rect(0, 0, 600, 150).fill(darkColor);
    doc.fillColor(primaryColor).fontSize(30).font('Helvetica-Bold').text('CHATPAY', 50, 50);
    doc.fillColor('#ffffff').fontSize(14).text('Strategic Future Roadmap: The Path to Global Ubiquity', 50, 85);
    doc.fillColor('#8696a0').fontSize(10).text('Generated by Antigravity AI Agent | April 2026', 50, 105);

    // --- PHASE 1: THE AGENTIC EXPLOSION (Current - 6 Months) ---
    doc.moveDown(5);
    doc.fillColor(primaryColor).fontSize(16).text('PHASE 1: THE AGENTIC EXPLOSION (0 - 6 MONTHS)', 50);
    doc.rect(50, doc.y + 5, 500, 1).fill(primaryColor);
    doc.moveDown(1);
    
    doc.fillColor(darkColor).fontSize(11).font('Helvetica');
    const phase1Items = [
        '• Omnichannel Domination: Fully scale the WhatsApp + Web Vault + PWA Trinity.',
        '• Community Escrow: Launch "Vouch Lists"—trusted vendor lists powered by the Agent.',
        '• PIDGIN v2: Fine-tune the AI Brain for deeper African vernacular nuances.',
        '• Agentic Deposits: Integrate automated payroll sweeps via Fincra/Bitnob.'
    ];
    phase1Items.forEach(item => {
        doc.text(item, { indent: 20 });
        doc.moveDown(0.5);
    });

    // --- PHASE 2: INSTITUTIONAL TRUST (6 - 12 Months) ---
    doc.moveDown(2);
    doc.fillColor(secondaryColor).fontSize(16).font('Helvetica-Bold').text('PHASE 2: INSTITUTIONAL TRUST (6 - 12 MONTHS)', 50);
    doc.rect(50, doc.y + 5, 500, 1).fill(secondaryColor);
    doc.moveDown(1);

    doc.fillColor(darkColor).fontSize(11).font('Helvetica');
    const phase2Items = [
        '• The Native Command Center: Launch the standalone iOS/Android Native Apps.',
        '• Biometric Authorization: Integrate FaceID/Fingerprint for high-value missions.',
        '• PSSP/MFB Licensing: Begin the transition to a fully regulated financial institution.',
        '• AI Credit Scoring: Use the Social Lending ledger to build alternative credit data.'
    ];
    phase2Items.forEach(item => {
        doc.text(item, { indent: 20 });
        doc.moveDown(0.5);
    });

    // --- PHASE 3: GLOBAL LIQUIDITY (12+ Months) ---
    doc.moveDown(2);
    doc.fillColor(accentColor).fontSize(16).font('Helvetica-Bold').text('PHASE 3: GLOBAL LIQUIDITY (12+ MONTHS)', 50);
    doc.rect(50, doc.y + 5, 500, 1).fill(accentColor);
    doc.moveDown(1);

    doc.fillColor(darkColor).fontSize(11).font('Helvetica');
    const phase3Items = [
        '• Cross-Border Arbitrage: Automated currency swap missions between NGN, USD, and BTC.',
        '• The Developer Portal: Open the ChatPay API for third-party "Agentic Plug-ins."',
        '• Sovereign Wealth: AI-managed hedge fund missions for high-net-worth users.',
        '• Hardware Wallets: Integration with physical security keys for ultimate safety.'
    ];
    phase3Items.forEach(item => {
        doc.text(item, { indent: 20 });
        doc.moveDown(0.5);
    });

    // Footer
    doc.fontSize(10).fillColor('#8696a0').text('Confidential Strategic Document - ChatPay Autonomous Corp.', 50, 750, { align: 'center' });
    
    doc.end();
};
