import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import { Wallet, ShieldCheck, FileText, Send, User } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
// Pages
const Dashboard = () => (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "p-6", children: [_jsxs("div", { className: "glass-card p-8 mb-6 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-32 h-32 bg-primary/20 rounded-full blur-3xl -mr-16 -mt-16" }), _jsx("p", { className: "text-text-muted text-sm font-medium uppercase tracking-wider mb-2", children: "Available Balance" }), _jsx("h1", { className: "text-4xl font-bold mb-6", children: "\u20A615,250.75" }), _jsxs("div", { className: "flex gap-4", children: [_jsxs("button", { className: "btn btn-primary", children: [_jsx(Send, { size: 18 }), " Send Money"] }), _jsx("button", { className: "btn", style: { background: 'var(--glass)' }, children: "Add Funds" })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "glass-card p-6", children: [_jsxs("h3", { className: "text-lg font-semibold mb-4 flex items-center gap-2", children: [_jsx(FileText, { size: 20, className: "text-accent" }), " Recent Transactions"] }), _jsx("div", { className: "space-y-4", children: [1, 2, 3].map(i => (_jsxs("div", { className: "flex justify-between items-center p-3 rounded-xl hover:bg-white/5 transition-colors", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "To @JohnDoe" }), _jsx("p", { className: "text-xs text-text-muted", children: "Yesterday, 4:20 PM" })] }), _jsx("p", { className: "font-semibold text-error", children: "-\u20A62,500.00" })] }, i))) })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsxs("h3", { className: "text-lg font-semibold mb-4 flex items-center gap-2", children: [_jsx(ShieldCheck, { size: 20, className: "text-success" }), " Verification Status"] }), _jsxs("div", { className: "bg-success/10 border border-success/20 p-4 rounded-xl mb-4", children: [_jsx("p", { className: "text-success text-sm font-medium", children: "Identity Verified (Tier 1)" }), _jsx("p", { className: "text-xs text-success/80 mt-1", children: "Daily limit: \u20A6500k" })] }), _jsx("button", { className: "text-primary text-sm font-medium hover:underline", children: "Upgrade to Tier 2 \u2192" })] })] })] }));
const KYC = () => (_jsx("div", { className: "p-6 max-w-lg mx-auto", children: _jsxs("div", { className: "glass-card p-8", children: [_jsx("h1", { className: "text-2xl font-bold mb-2", children: "Complete Verification" }), _jsx("p", { className: "text-text-muted mb-8", children: "Let's get your account fully compliant to unlock higher limits." }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Document Type" }), _jsxs("select", { className: "w-full bg-white/5 border border-white/10 rounded-xl p-3 text-white", children: [_jsx("option", { children: "BVN Verification" }), _jsx("option", { children: "NIN (Digital ID)" }), _jsx("option", { children: "International Passport" })] })] }), _jsxs("div", { className: "border-2 border-dashed border-white/10 rounded-2xl p-8 text-center hover:border-primary/50 transition-colors cursor-pointer", children: [_jsx(FileText, { className: "mx-auto mb-4 text-text-muted", size: 40 }), _jsx("p", { className: "font-medium", children: "Click to upload document" }), _jsx("p", { className: "text-xs text-text-muted mt-2", children: "PDF, JPG, PNG (Max 5MB)" })] }), _jsx("button", { className: "btn btn-primary w-full", children: "Submit for Review" })] })] }) }));
const Checkout = () => (_jsx("div", { className: "p-6 max-w-lg mx-auto", children: _jsxs("div", { className: "glass-card p-8", children: [_jsxs("div", { className: "flex justify-between items-start mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold", children: "Secure Checkout" }), _jsx("p", { className: "text-text-muted mt-1", children: "Invoice #INV-29384" })] }), _jsx("div", { className: "bg-primary/10 p-3 rounded-2xl", children: _jsx(Wallet, { className: "text-primary" }) })] }), _jsxs("div", { className: "bg-white/5 rounded-2xl p-6 mb-8", children: [_jsxs("div", { className: "flex justify-between mb-2", children: [_jsx("span", { className: "text-text-muted", children: "Service" }), _jsx("span", { className: "font-medium", children: "Logo Design" })] }), _jsxs("div", { className: "flex justify-between border-t border-white/10 pt-4 mt-2", children: [_jsx("span", { className: "text-text-muted", children: "Amount" }), _jsx("span", { className: "text-2xl font-bold", children: "\u20A650,000.00" })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("button", { className: "btn btn-primary w-full p-6 text-lg", children: "Pay with ChatPay Wallet" }), _jsx("button", { className: "btn w-full bg-white/5 border border-white/10", children: "Other Payment Methods" })] }), _jsx("p", { className: "text-center text-xs text-text-muted mt-8", children: "Protected by Fincra & ChatPay Secure Protocol" })] }) }));
const AdminDashboard = () => (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "flex justify-between items-center mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold title-gradient", children: "God Mode" }), _jsx("p", { className: "text-text-muted", children: "Master Control & Analytics" })] }), _jsx("div", { className: "flex gap-4", children: _jsxs("div", { className: "glass-card px-4 py-2 flex items-center gap-2", children: [_jsx("div", { className: "w-2 h-2 bg-success rounded-full animate-pulse" }), _jsx("span", { className: "text-xs font-medium", children: "System Online" })] }) })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-6 mb-8", children: [
                { label: 'Total TPV', value: '₦4.2M', growth: '+12%', icon: Wallet, color: 'text-primary' },
                { label: 'Active Users', value: '1,280', growth: '+5%', icon: User, color: 'text-secondary' },
                { label: 'Successful KYC', value: '850', growth: '66%', icon: ShieldCheck, color: 'text-success' },
                { label: 'AI Confidence', value: '98.2%', growth: 'Stable', icon: ShieldCheck, color: 'text-accent' },
            ].map((m, i) => (_jsxs("div", { className: "glass-card p-6", children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsx("div", { className: `p-2 rounded-lg bg-white/5 ${m.color}`, children: _jsx(m.icon, { size: 20 }) }), _jsx("span", { className: "text-xs text-success font-medium", children: m.growth })] }), _jsx("p", { className: "text-text-muted text-xs mb-1 uppercase tracking-wider", children: m.label }), _jsx("h2", { className: "text-2xl font-bold", children: m.value })] }, i))) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "lg:col-span-2 glass-card p-6", children: [_jsxs("h3", { className: "text-lg font-semibold mb-6 flex items-center gap-2", children: [_jsx(FileText, { size: 20, className: "text-primary" }), " Live Transaction Pulse"] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left", children: [_jsx("thead", { children: _jsxs("tr", { className: "text-text-muted text-xs uppercase border-b border-white/10", children: [_jsx("th", { className: "pb-4 font-medium", children: "User" }), _jsx("th", { className: "pb-4 font-medium", children: "Type" }), _jsx("th", { className: "pb-4 font-medium", children: "Amount" }), _jsx("th", { className: "pb-4 font-medium", children: "Status" }), _jsx("th", { className: "pb-4 font-medium", children: "Agent" })] }) }), _jsx("tbody", { className: "text-sm", children: [
                                            { user: '+234 812...', type: 'P2P Transfer', amount: '₦15,000', status: 'Success', agent: 'AI_GPT4o' },
                                            { user: '+234 905...', type: 'Utility Bill', amount: '₦2,500', status: 'Pending', agent: 'AI_GPT4o' },
                                            { user: '+234 703...', type: 'Funding', amount: '₦50,000', status: 'Success', agent: 'System' },
                                        ].map((t, i) => (_jsxs("tr", { className: "border-b border-white/5 hover:bg-white/5 transition-colors", children: [_jsx("td", { className: "py-4 font-medium", children: t.user }), _jsx("td", { className: "py-4", children: t.type }), _jsx("td", { className: "py-4 font-bold", children: t.amount }), _jsx("td", { className: "py-4", children: _jsx("span", { className: `px-2 py-1 rounded-full text-[10px] ${t.status === 'Success' ? 'bg-success/10 text-success' : 'bg-accent/10 text-accent'}`, children: t.status }) }), _jsx("td", { className: "py-4 text-xs text-text-muted", children: t.agent })] }, i))) })] }) })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsxs("h3", { className: "text-lg font-semibold mb-6 flex items-center gap-2", children: [_jsx(ShieldCheck, { size: 20, className: "text-accent" }), " Pending KYC Review"] }), _jsx("div", { className: "space-y-4", children: [1, 2, 3].map(i => (_jsxs("div", { className: "p-4 rounded-xl bg-white/5 border border-white/5", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsxs("p", { className: "font-medium text-sm", children: ["User_", i, "92"] }), _jsx("span", { className: "text-[10px] text-text-muted", children: "2 mins ago" })] }), _jsx("p", { className: "text-xs text-text-muted mb-4", children: "Doc type: NIN (Naira ID Card)" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { className: "flex-1 bg-success/20 text-success text-xs py-2 rounded-lg hover:bg-success/30", children: "Verify" }), _jsx("button", { className: "flex-1 bg-error/20 text-error text-xs py-2 rounded-lg hover:bg-error/30", children: "Reject" })] })] }, i))) })] })] })] }));
function App() {
    return (_jsx(Router, { children: _jsxs("div", { className: "min-h-screen flex flex-col", children: [_jsxs("nav", { className: "glass-card mx-4 my-4 p-4 flex justify-between items-center sticky top-4 z-50", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2", children: [_jsx("div", { className: "w-10 h-10 bg-primary rounded-xl flex items-center justify-center font-bold text-xl shadow-lg shadow-primary/20", children: "C" }), _jsx("span", { className: "font-bold text-xl tracking-tight", children: "ChatPay" })] }), _jsxs("div", { className: "flex gap-4 items-center", children: [_jsx(Link, { to: "/admin", className: "text-xs font-bold text-text-muted hover:text-primary transition-colors uppercase tracking-widest", children: "God Mode" }), _jsx(Link, { to: "/kyc", className: "p-2 hover:bg-white/5 rounded-lg transition-colors", children: _jsx(ShieldCheck, { size: 22 }) }), _jsx("div", { className: "w-10 h-10 bg-white/5 rounded-full flex items-center justify-center border border-white/10", children: _jsx(User, { size: 20 }) })] })] }), _jsx("main", { className: "flex-1", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "/kyc", element: _jsx(KYC, {}) }), _jsx(Route, { path: "/pay/:id", element: _jsx(Checkout, {}) }), _jsx(Route, { path: "/admin", element: _jsx(AdminDashboard, {}) })] }) }), _jsx("div", { className: "fixed bottom-8 right-8", children: _jsx("button", { className: "w-16 h-16 bg-primary rounded-full flex items-center justify-center shadow-2xl shadow-primary/40 hover:scale-110 transition-transform", children: _jsx(Send, { size: 24, className: "text-white" }) }) })] }) }));
}
export default App;
//# sourceMappingURL=App.js.map